<a href="https://colab.research.google.com/github/bidallei/MIAAD-UACJ/blob/main/Practica04_263150.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Práctica 4: Unidad 1. Manipulación de matrices**
---

Alumno: Álvaro Hernandez Jarquín<br>
Seminario: Programación para analítica descriptiva y predictiva
---

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:



1. Suma ambas matrices.
2. Resta la segunda matriz de la primera.
3. Multiplica la primera matriz por 2.
4. Realiza una multiplicación matricial entre las dos matrices.









In [ ]:
#Importamos la biblioteca Numpy con un alias
import numpy as np

# Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:
matriz_uno = np.random.randint(1, 11, size=(3,3))
matriz_dos = np.random.randint(1, 11, size=(3,3))
print(f'Matriz uno: \n{matriz_uno}')
print()
print(f'Matriz dos: \n{matriz_dos}')
print()

# 1. Suma ambas matrices.
suma_matrices = matriz_uno + matriz_dos
print(f'Suma de ambas matrices: \n{suma_matrices}')
print()

# 2. Resta la segunda matriz de la primera.
resta_matrices = matriz_uno - matriz_dos
print(f'Resta la segunda matriz de la primera: \n{resta_matrices}')
print()

# 3. Multiplica la primera matriz por 2.
multiplicacion_matriz = matriz_uno * 2
print(f'Multiplicacion de la primera matriz por 2: \n{multiplicacion_matriz}')
print()

# 4. Realiza una multiplicación matricial entre las dos matrices.
multiplicacion_matrices = np.dot(matriz_uno, matriz_dos)
# Otra opción sería: multiplicacion_matrices = matriz_uno @ matriz_dos
print(f'Multiplicacion matricial entre ambas matrices: \n{multiplicacion_matrices}')

Matriz uno: 
[[ 5  8  5]
 [ 4  5 10]
 [ 7  1  9]]

Matriz dos: 
[[7 1 4]
 [5 1 5]
 [4 4 7]]

Suma de ambas matrices: 
[[12  9  9]
 [ 9  6 15]
 [11  5 16]]

Resta la segunda matriz de la primera: 
[[-2  7  1]
 [-1  4  5]
 [ 3 -3  2]]

Multiplicacion de la primera matriz por 2: 
[[10 16 10]
 [ 8 10 20]
 [14  2 18]]

Multiplicacion matricial entre ambas matrices: 
[[ 95  33  95]
 [ 93  49 111]
 [ 90  44  96]]
